version: '3'

services:
    db:
        image: mysql:8.0.19
        ports:
            - 3306:3306
        container_name: mysql_container
        environment:
            - MYSQL_ROOT_PASSWORD=admin12345@@
            - MYSQL_PASSWORD=admin12345@@
            - MYSQL_USER=root

    docker_backend:
        image: backend_image:latest
        container_name: backend_container
        ports:
           - 8080:8080
        depends_on:
            - db
